# Project: Race to Twelve
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
RES      = obj/Race_to_Twelve_private.res
OBJ      = obj/main.o obj/render.o obj/font.o obj/game.o obj/texture.o obj/lodepng.o $(RES)
LINKOBJ  = obj/main.o obj/render.o obj/font.o obj/game.o obj/texture.o obj/lodepng.o $(RES)
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -L"C:/Users/Emman/Documents/DEV Projects/Race to Twelve OpenGL GLUT/lib" -mwindows -lopengl32 lib/glut32.lib lib/glext.lib -m32
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = "bin/Race to Twelve.exe"
CXXFLAGS = $(CXXINCS) -m32 -std=c++11
CFLAGS   = $(INCS) -m32
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

obj/main.o: src/main.cpp
	$(CPP) -c src/main.cpp -o obj/main.o $(CXXFLAGS)

obj/render.o: src/render.cpp
	$(CPP) -c src/render.cpp -o obj/render.o $(CXXFLAGS)

obj/font.o: src/font.cpp
	$(CPP) -c src/font.cpp -o obj/font.o $(CXXFLAGS)

obj/game.o: src/game.cpp
	$(CPP) -c src/game.cpp -o obj/game.o $(CXXFLAGS)

obj/texture.o: src/texture.cpp
	$(CPP) -c src/texture.cpp -o obj/texture.o $(CXXFLAGS)

obj/lodepng.o: src/lodepng.cpp
	$(CPP) -c src/lodepng.cpp -o obj/lodepng.o $(CXXFLAGS)

obj/Race_to_Twelve_private.res: Race_to_Twelve_private.rc 
	$(WINDRES) -i Race_to_Twelve_private.rc -F pe-i386 --input-format=rc -o obj/Race_to_Twelve_private.res -O coff 

